# Generated by Django 3.2 on 2023-04-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20230329_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
